<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Index</title>
</head>
<body>
	<ul>	
		<li><a href="/Home/HelloWorld">Hello World</a></li>
		<li><a href="/Home/Condition">Condition</a></li>
		<li><a href="/Home/Loops">Loops</a></li>
		<li><a href="/Home/Layout">Layout</a></li>
		<li><a href="/Home/Partials">Partials</a></li>
	</ul>
	
	
</body>
</html>
